version: '3.8'

volumes:
  nextcloud:
  db:

services:
  nextcloud_db:
    image: mariadb:10.6
    container_name: nextcloud_maria_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud:29.0.3
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - 5075:80
    depends_on:
      - nextcloud_db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=http://localhost:5001 http://localhost https://localhost:5001 https://localhost
      - REDIS_HOST=redis

  redis:
    image: redis:7.2.5
    container_name: nextcloud-redis
    volumes:
      - ./redis:/data